### PR TITLE
Fix broken links and add Discord redirect

### LINKED ISSUE #61: Permalink to our Discord invite from our site
In the past, we had a redirect so that we could link to https://sourcecred.io/discord-invite and it would bring you to an invite to join the SC discord server. (See: https://github.com/sourcecred/sourcecred/pull/550)

As of the migration to docasaurus, this no longer works. Let's add it back. For simplicity, we may want to make the url just be https://sourcecred.io/discord

### PR DESCRIPTION
**Pull request by hammadj**
Closes #61

Fixed some mis-configured links in the navbar and added the Discord redirect back so people who visit sourcecred.io/discord will get sent to our Discord server

### CODE REVIEW

File: src/pages/discord.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import React from 'react';
+
+const Discord = () => {
+  React.useEffect(() => {
+    window.location.replace('https://discord.gg/SXreMyQ')
+  }, [])
+  
+  return null;
+};
```
Comment (Beanow) [inline src/pages/discord.js:9]: Interesting approach to doing this.
For static sites I've most commonly seen usage of meta as this works for noscript browsers.
```html
<meta http-equiv="refresh" content="0; url=http://example.com/">
```
Though not sure if going off the domain gives any extra CORS limitations.

Comment (hammadj) [reply src/pages/discord.js]: @Beanow Good point, changed to using meta-tags instead so it works for no script browsers

Comment (Beanow) [reply src/pages/discord.js]: Also, we can let the server handle it seems like.
https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

Comment (hammadj) [reply src/pages/discord.js]: I would rather handle it on the client side since server configuration isn't version controlled or visible to everyone. Makes it more portable too if we decide to move to something other than Netlify

Comment (Beanow) [reply src/pages/discord.js]: Isn't the netlify.toml something you can store in the repo?

Comment (hammadj) [reply src/pages/discord.js]: Yea, but it also couples us to Netlify vs having a generic solution. Might also cause weirdness if there's naming collisions or something with the routes defined on the client level

Comment (Beanow) [reply src/pages/discord.js]: Avoiding vendor lock-in is an argument I can get behind :P
